  CASE 
    WHEN tm.origin = 1 then 'Customer'
    WHEN tm.origin = 2 then 'Agent'
    WHEN tm.origin = 3 then 'email'
    WHEN tm.origin = 4 then 'System trigger'
    WHEN tm.origin = 5 then 'Live chat'
    WHEN tm.origin = 6 then 'Offline chat message'
    WHEN tm.origin = 7 then 'System email'
    WHEN tm.origin = 8 then 'Ticket web form'
    WHEN tm.origin = 9 then 'Tickets API'
    WHEN tm.origin = 10 then 'Recurring schedule'
    WHEN tm.origin = 11 then 'Jira issue'
    WHEN tm.origin = 12 then 'Redmine issue'
    WHEN tm.origin = 13 then 'Answered call'
    WHEN tm.origin = 14 then 'Outbound call'
    WHEN tm.origin = 15 then 'Missed call'
    WHEN tm.origin = 16 then 'Abandoned call'
    WHEN tm.origin = 17 then 'Remote access [DEPRECATED]'
    WHEN tm.origin = 18 then 'WhatsApp'
    WHEN tm.origin = 19 then 'Integrated Movidesk instance'
  END
